### ISSUE TITLE
How to use ansible on windows

### ISSUE THREAD

**Issue by shashisd** [SeleniumHQ/ansible-selenium#1]
Hi All,
Please let me know how to use ansible command on windows OS,i am unable to install 
ansible-galaxy install ddavison.selenium on win.

**Comment by ddavison** [comment]
How to use Ansible on Windows is a little out-of-scope for this repository.. when I asked you to write an issue, I wanted you to attempt to get it working first.. these issues will be reserved for issues regarding this specific module.  

Here is an introduction to using Ansible on windows: http://docs.ansible.com/ansible/intro_windows.html

and here is the getting started page for Ansible: http://docs.ansible.com/ansible/intro_getting_started.html

if you need help with this *specific module*, i'll be happy to do that - but It's expected if you use this role, that you know how to use ansible :)

Hopefully those links help you.
