### ISSUE TITLE
Please fix the tags

### ISSUE THREAD

**Issue by rgarrigue** [SeleniumHQ/ansible-selenium#12]
Hello

This repo's tagged with a vX.Y.Z and a X.Y.Z, which is confusing ansible-galaxt and preventing installation. I had to specify `version: 3.3.1` in my `requirements.yml` to get it installed.

Please fix the tags.

**Comment by ddavison** [comment]
apologies for that - the releases were initially intended to match the Selenium version that ansible was specifying.

E.g: https://github.com/SeleniumHQ/ansible-selenium/blob/master/library/selenium#L307

however i concur this is bad design. i've went ahead and removed all tagged releases and starting fresh with 1.0.1 semver. sorry about that!
