### ISSUE TITLE
ansible-doc problem

### ISSUE THREAD

**Issue by Hipska** [SeleniumHQ/ansible-selenium#9]
It seems that this module is not compatible with `ansible-doc`:
```
$ ansible-doc selenium -v
Using /Users/Hipska/.ansible.cfg as config file
 [ERROR]: unable to parse /usr/local/share/ansible/modules/selenium.py

unable to parse /usr/local/share/ansible/modules/selenium.py
 [ERROR]: module selenium has a documentation error formatting or is missing documentation To see exact traceback use -vvv
```
Or did I do something wrong? I made a symlink from the file in library to the modules directory. This is my Ansible version:
```
$ ansible --version
ansible 2.3.0.0
  config file = /Users/Hipska/.ansible.cfg
  configured module search path = [u'/usr/local/share/ansible/modules/']
  python version = 2.7.13 (default, Feb  9 2017, 15:11:16) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by Hipska** [comment]
I first thought it might be related to my Ansible version. I had this also with 2.2 but as you see, after upgrading it still doesn't work. The older version produced a slightly different message:
```
ERROR! module selenium missing documentation (or could not parse documentation): Parsing produced an empty object.
```

**Comment by ddavison** [comment]
could you do me a favor and [create a gist](https://gist.github.com) of `$cat /usr/local/share/ansible/modules/selenium.py` ? I want to make sure that this is the actual module you're referring to.  thanks!

**Comment by Hipska** [comment]
It is exactly the same as library/selenium file in this repository: https://gist.github.com/Hipska/41edf72663db4390eaf0196ccb19a100

**Comment by Hipska** [comment]
Hi @ddavison, almost 2 years later.. Anything?
